/chart/balance/balance:
  get:
    tags:
      - charts
    summary: Dashboard chart with balance information.
    description: |
      This endpoint returns the data required to generate a chart with balance information.
    operationId: getChartBalance
    parameters:
      _tpl_correlationParameter,3:
      _tpl_mandatoryDateRangeParameters,3:
      _tpl_periodParameter,3:
      _tpl_preselectedParameter,3:
      - in: query
        name: accounts[]
        description: |
          Limit the chart to these asset accounts or liabilities. Only asset accounts and liabilities will be accepted. Other types will be silently dropped.
          
          This list of accounts will be OVERRULED by the `preselected` parameter.
        required: false
        explode: true
        schema:
          type: array
          items:
            type: integer
            format: int64
          example: [ 1, 2, 3 ]
    responses:
      _tpl_unauthenticatedResponse,3:
      _tpl_notFoundResponse,3:
      _tpl_badRequestResponse,3:
      _tpl_validationErrorResponse,3:
      _tpl_internalExceptionResponse,3:
      "200":
        description: Line chart oriented chart information. Check out the model for more details. Each entry is a line (or bar) in the chart.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChartLine'
