ConfigValueUpdateFilter:
  type: string
  enum:
    - configuration.is_demo_site
    - configuration.permission_update_check
    - configuration.last_update_check
    - configuration.single_user_mode
    - configuration.enable_exchange_rates
    - configuration.use_running_balance
    - configuration.enable_external_map
    - configuration.enable_external_rates
    - configuration.allow_webhooks
    - configuration.valid_url_protocols
